[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****
The goal of this project is to develop an application which is able to store user routes in a *decentralized* manner but still manages to share these decentralized routes with other users.

The technologies that will be used in the development of this application will be _React_ in the front-end and a _SOLID_ based server in the back-end.

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****
These are the *functional* requirements our application will provide:

. Data stored in a decentralized way (separated from the application). Each user will have their own pods for the routes to be stored on.

. The users will be able to view their routes in a map.

. Users can share the data stored in their pods with other single users or with groups of users selected by them.

. Users will get a notification everytime s route gets shared with them.



=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2"]
|===
|Role/Name|Expectations
| *_Teachers of the course_* | The teachers of the course expect the students to deliver a project which is completely functional and fulfills the requirements provided.
| *_Users_* | The people who will use the application expect it to be easy to use, functional and secure.
| *_Inrupt_* | Tim Berners Lee ans his team expect to us to provide an application which help in the decentralization of the web by using _SOLID_ and its principles.
| *_Future Developers_* | Next year students and other developers wold expect the code to be understandable and easy to maintain.
| *_The Team_* | As programmers, we expect to learn new development evironments and develop a final product that we can be proud of.
