[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

.Technical Constraints
[width="80%",options="header"]
|=========================================================
|Constraint |Description 

|React | The appplication must work with react
|Solid| The application must work with solid

|=========================================================

.Organizational Constraints
[width="80%",options="header"]
|=========================================================
|Constraint |Description 

|Team | The team is composed of seven people
|Time | The application must be completed before the end of the curse
|Scope | Decentralized application for managing routes 
|Data |  Data storage is separated from the app

|=========================================================
