[[section-system-scope-and-context]]
== System Scope and Context

Viade is an application that will allow the user to store routes, view them on a map, share them with friends who are also using Viade, alongside multimedia like videos and pictures of said routes. 

Storing routes can be done either by importing them from other applications or by using Viade as a route tracker, meaning that if used from a mobile device, it can use its GPS capabilities in order to create and store the route on the go.

Our objective is to develop Viade as a decentralized application, so users will be the ones storing all their information and thus, increasing the privacy and data security of the system, by not having any central server to store and manage said data.

=== Business Context

[plantuml,"Business context diagram",png]
----
:User A: as A

node "System" as Sys{
}

:User B: as B

database "A's POD" as AP {
    folder Routes as r1
}

database "B's POD" as BP {
    folder inbox as r2
}

cloud "Map" as Map{
}

A -right-> Sys : share to B
A -[#0000ff]right-> Sys : My routes
Sys -[#00ff00]right-> AP: get A's stored routes
r1 -[#00ff00]-> Sys
Sys -[#0000ff]down-> Map : set routes\n on map
Map -[#0000ff]up-> A : show\n routes
Sys ---> r2 : mail with\n route URL
Sys -right-> B : User B is notified
B -down-> r2 : User B\n access route

legend right
    |= Color |= Description |
    | <size:11><back:#ff0000>           </back></size>|    Share routes |
    | <size:11><back:#0000ff>           </back></size>|    See my routes |
    | <size:11><back:#00ff00>           </back></size>|    Common process |
endlegend
----

=== Technical Context


[plantuml,"Technical context diagram",png]
----
title deployment - Technical Context\n

:Sender: as U1
:Receiver: as U2

frame ViaDe as GUI1 {
    component [Graphic User\nInterface 1] as gui1
}

frame ViaDe as GUI2 {
    component [Graphic User\nInterface 2] as gui2
}

database "POD 1" as P1 {
    folder Routes as r1
}

database "POD 2" as P2 {
    folder Routes as r2
}

U1 --> GUI1: Web Browser/\nNative App
U2 --> GUI2: Web Browser/\nNative App

GUI1 ----> P1: Store route\n(https)
P1 ----> GUI1: View route\n(https)
GUI1 ----> P2: Share route\n(https)
P2 -up---> GUI2: Notify/\nview shared route\n(https)

----

[options="header",cols="2,2"]
|===
|Business interface|Channel
|*_Sharing or storing routes_*  | Upload to a POD (https).
|*_Viewing routes_*  | Download from a POD (https).
|===
