[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Add track>


* A user can add tracks to their pod.

[plantuml,"Sequence diagram 1",png]
----
actor Alice
participant Tracks_List
participant Track_Controller
participant Track_Parser
participant Pod_Controller
entity Track

Alice -> Tracks_List: Select add track

Tracks_List -> Track_Controller: Upload track file (json-ld)
activate Track_Controller



Track_Controller -> Pod_Controller: Store track
activate Pod_Controller
Pod_Controller -> Track :Use
Pod_Controller -> Track_Controller: Return
deactivate Pod_Controller
deactivate Track_Controller


Tracks_List -> Track_Controller :Get Tracks
activate Track_Controller
Track_Controller -> Pod_Controller :Get Tracks
activate Pod_Controller
Pod_Controller -> Track :Use
Pod_Controller -> Track_Controller: Return
deactivate Pod_Controller
Track_Controller -> Track_Parser :Parse Track
activate Track_Parser
Track_Parser -> Track_Controller :Return
deactivate Track_Parser
Track_Controller -> Tracks_List: Return
deactivate Track_Controller
Tracks_List -> Tracks_List :Refresh
----

=== <View track>


* A user can add see tracks from their pod.


=== <Share track>


* A user can share tracks from their pod to friends.