[[section-deployment-view]]


== Deployment View

- Computer with internet access
- Node.js
- A Solid POD by registering with either Inrupt or Solid Community. 
- For being able to fully use the application, you'll need to do the following:
    a. For a correct functioning of the application, you must be logged in into your Solid POD outside of the application.
    b. Give total control to the application over your POD when first logging in (or from your POD).
    c. In privacy settings for your inbox folder, create a rule such that *anyone* can make *submissions* to it.
    d. In the Viade folder that the app will generate in your POD, create a rule such that *anyone* or *your friends*, being the latter the recommended one for security reasons, can *view the contents* inside it.
    e. For the *sharing* functionality to work properly, both you and the person who you want to share a route with, must have each other added as a *friend* in Solid.
    e. Routes imported into the application must follow the JSON-LD syntax of the ViadeSpec, similar to the following example:

.JSON-LD format example:
[#src-listing] 
[source,json]  
---- 
{
  "@context": {
    "@version": 1.1,
    "comments": {
      "@id": "viade:comments",
      "@type": "@id"
    },
    "description": {
      "@id": "schema:description",
      "@type": "xsd:string"
    },
    "media": {
      "@container": "@list",
      "@id": "viade:media"
    },
    "name": {
      "@id": "schema:name",
      "@type": "xsd:string"
    },
    "points": {
      "@container": "@list",
      "@id": "viade:points"
    },
    "latitude": {
      "@id": "schema:latitude",
      "@type": "xsd:double"
    },
    "longitude": {
      "@id": "schema:longitude",
      "@type": "xsd:double"
    },
    "elevation": {
      "@id": "schema:elevation",
      "@type": "xsd:double"
    },
    "author": {
      "@id": "schema:author",
      "@type": "@id"
    },
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "schema": "http://schema.org/",
    "viade": "http://arquisoft.github.io/viadeSpec/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "name": "Route test 1",
  "author": "https://luispresacollada.solid.community/profile/card#me",
  "description": "This is a test to see the output of the JsonLDConversor",
  "comments": "http://inrupt.luispc1998/viade/comments/routeComments/commentExample.json",
  "media": [
    {
      "url": "http://inrupt.luispc1998/viade/resources/imagen.jpg"
    },
    {
      "url": "http://inrupt.angelixus/viade/resources/video.mp4"
    },
    {
      "url": "http://inrupt.raupemol/viade/resources/foto.png"
    },
    {
      "url": "http://inrupt.luispc1998/viade/resources/video3.mp4"
    }
  ],
  "waypoints": [
    {
      "name": "Name for the waypoint",
      "description": "Description of the waypoint",
      "latitude": 45.123,
      "longitude": 34.121,
      "elevation": 34
    },
    {
      "name": "Computer Science School",
      "description": "Become a good engineer with us",
      "latitude": 45.123,
      "longitude": 34.121,
      "elevation": 34
    }
  ],
  "points": [
    {
      "latitude": 45.123,
      "longitude": 34.121,
      "elevation": 34
    },
    {
      "latitude": 46.123,
      "longitude": 34.121,
      "elevation": 36
    },
    {
      "latitude": 47.123,
      "longitude": 34,
      "elevation": 39
    },
    {
      "latitude": 48.123,
      "longitude": 32.121,
      "elevation": 40
    },
    {
      "latitude": 49.123,
      "longitude": 34.121,
      "elevation": 43
    },
    {
      "latitude": 40.123,
      "longitude": 32.121,
      "elevation": 46
    },
    {
      "latitude": 50.123,
      "longitude": 33.121,
      "elevation": 50
    },
    {
      "latitude": 53.123,
      "longitude": 34.121,
      "elevation": 55
    },
    {
      "latitude": 54.123,
      "longitude": 34.121,
      "elevation": 56
    },
    {
      "latitude": 55.123,
      "longitude": 35.121,
      "elevation": 50
    },
    {
      "latitude": 55.123,
      "longitude": 34.121,
      "elevation": 45
    }
  ]
}
----


