[[section-concepts]]
== Cross-cutting Concepts

=== Route
It is the main concept in this application, representing a sequence of points in the space.

* For the user, they are shown as a graphic polyline in a map.
* On the logic of the system, they are treated as a collection of coordinates.
* The coordinates are stored in the PODs.

=== Solid POD
Storage device based on Solid that stores user data in a private and decentralized approach. In our application, it's main uses will be:

* Storing pictures. Imported pictures will be stored in the user's Solid POD. This also includes any multimedia the user has decided to add to the route.

* Sharing pictures with other users by allowing them to retrieve it and store them in their own PODs.

=== Notification

It is the core element in the communication between different users. 

* A *notification* is sent everytime a user *shares a route* with any friend.

* It contains the URL in the sender's POD of the resource that is being shared, f.i User A, which has `https://usera.pod` as his POD URL, shares a route with User B, whose
POD is `https://userb.pod`. Thus, a notification will arrive to `https://userb.pod/inbox` with `https://usera.pod/public/pictures/route.json` as the content.

* In order to achieve interoperability, we need to agree about *how* this notification works. First, the different parts that shape 
the notification, f.i content, date, sender, receiver, etc. Equally, the discussion about *where* the notification has to be sent, f.i folder `inbox/` in the POD.

=== JSON-LD
Method of encoding Linked Data using JSON. Used to store the pictures for sharing between PODs so that our application can be compatible with the pictures done by users of other Viade applications, provided that they are storing the pictures in JSON-LD and following the Viade Specification.

=== Viade Specification
Linked Data specification developed by the students of Software Architecture for making our apps and pictures compatible with each other by documenting a common data model.

=== Solid POD friends
Users may add other users as friends in the Solid PODs, but as stated in Deployment View, for the sharing capabilitites to work, friendships must be reciprocal.
