[[section-concepts]]
== Cross-cutting Concepts

=== Route
It is the main concept in this application, representing a sequence of points in the space.

* For the user, they are shown as a graphic polyline in a map.
* On the logic of the system, they are treated as a collection of coordinates.
* The coordinates are stored in the PODs.

=== Solid POD
Storage device based on Solid that stores user data in a private and decentralized approach. In our application, it's main uses will be:

* Storing routes. Imported routes will be stored in the user's Solid POD. This also includes any multimedia the user has decided to add to the route.

* Sharing routes with other users by allowing them to retrieve it and store them in their own PODs.

=== JSON-LD
Method of encoding Linked Data using JSON. Used to store the routes for sharing between PODs so that our application can be compatible with the routes done by users of other Viade applications, provided that they are storing the routes in JSON-LD and following the Viade Specification.

=== Viade Specification
Linked Data specification developed by the students of Software Architecture for making our apps and routes compatible with each other by documenting a common data model.

=== Solid POD friends
Users may add other users as friends in the Solid PODs, but as stated in Deployment View, for the sharing capabilitites to work, friendships must be reciprocal.
