[[section-technical-risks]]
== Risks and Technical Debts

=== Risks
Because of the complexity of this project and the use of technologies we have never tried before, the team may encounter some problems while developing the application. These are some of the problems we expect to have and, hopefully, surpass.

. *Use of _React_:* No member of the team has ever worked with _React_ , so learning how this new language works will probably slow down the development.
. *Use of _SOLID_:* None of us has ever worked with servers before and we had never heard of _SOLID_, so it is a scary and hard topic to tackle for all members of the team.
. *Group work:* Because we are working in a group with a big number of members we may face some troubles when trying to communicate, organize and come to an agreement on some important decisions.
. *Use of git:* Although this is not the first time we are using git we are still not experts on the subject (especially when using it from a command window), so some branch merges and conflicts may be difficult to perform and solve.
. *Lack of experience:* As we are still third year students, there are a lot of libraries and helpful tools we don't know about, and some others that will be hard for us to use. Because of this lack of knowledge and experience, we may pass on using some unknown beneficial tools and, instead, waste our time trying to use more difficult ones.

=== Technical Debt
Because of the risks mentioned before and some decisions taken by the team, we are aware of some aspects of our application that could be improved. These are some that we hope to fix in the near future.

. *Few Test:* Until now we have chosen to focus more on implementation than testing so we hope to take our codecov to, at least, 60% by the next deliverable.
. *Unnecesary code:* Due to the generator we used at the beggining, we have a lot of code we don't use and/or don't understand. This code should be deleted to avoid security issues and a dirty project.